#source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'

pod 'CMUtils', :git => 'https://github.com/imjerrybao/CMUtils.git'
pod 'BlocksKit', '~> 2.2.5'
pod 'AFNetworking', '~> 2.5.2'
pod 'JSONModel', '~> 1.0.2'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'FMDB', '~> 2.5'
pod 'UMengAnalytics'
pod 'JKBigInteger', '~> 0.0.1'
pod 'PEPhotoCropEditor', '~> 1.3.1'
pod 'Masonry', '~> 0.6.1'
pod 'UITextView+Placeholder'
pod 'IQKeyboardManager'
pod 'pop', '~> 1.0'
pod 'UITableView+FDTemplateLayoutCell'
pod 'DACircularProgress'
pod 'FDFullscreenPopGesture', '~> 1.1'
